

function Home() {
    return (
        <div>
            <div>
                Hello World! I am Jacob Lin

                This website is a work in progress. I'll be updating the look and adding more experiences as I go :{')'}.
            </div>
            <div>
                <h1>Critique</h1>
                <p>Linked above is the personal website of a great friend of mine, Christopher Cha. He is an eccentric and awesome person and I always love to listen to his thoughts about all the media he consumes. He’s a great person to go to for recommendations. Please do go check him out :{')'}</p>
                <p>His website has been a great source of inspiration for me to create my own personal website which you are viewing now! There are many elements that I think are great about his site and have attempted to incorporate into my own site, but there are also several elements that I approached differently and I hope you can see those differences here!</p>
                <p>First off, let’s start by defining the purpose of a personal website. A personal website is a place for you to express yourself and show who you are to the world. It may be that you want to show off your accomplishments or you just want to share a piece of your personality with the world.</p>
                <p>Towards this definition, Chris focuses on creating a more professional website to present his accomplishments specifically in computer science to the world. This website functions more as a resume website targeted towards recruiters. Despite this goal, he blends many personal elements into the website giving the viewer a sense of his personality and enhancing the experience going through the website.</p>
                <p>This experience begins with the title, “chris cha is trying new things”. Already, there is a sense of his character behind those words: someone who is explorative, unafraid to head into the unknown, creative and unique. From these implications, the audience is drawn into learning who Chris is, curious to see where he is headed. What “new things” is he trying to do, and will explore in the future? This question is quickly answered when he introduces himself as a student at UCSD and states his professional interests, setting a professional tone to his website, counterbalancing with the casual tone from his title. He then jumps back to a more casual tone, talking about his personal interests. This back and forth between professional and casual merges into a professional but casual feel for the site which then extends to his character. This kind of character appeals to the target audience, recruiters, as they are not just looking for accomplished individuals, but also individuals who would potentially be fun to work with. He wraps the introduction up with a statement that his site is still a work in progress, referencing back to how he began, and reminding the audience of his character and adding to it a sense of responsibility and hard work.</p>
                <p>I enjoy the professional but casual feel that his introduction built for his site, but the positioning of this introduction in the site can potentially detract from this exposition. It is placed on the left side of the site and takes up about a third of the website. The rest is filled with his projects and experiences. While those elements are the most important to present, they are enhanced if viewed with the context of the introduction. It would be best if the introduction is presented first to the viewer as a separate page or higher up on the page and then the site would progress to the projects and experiences. By placing his introduction to the left third, it is marginalized and is more likely to be skipped.</p>
                <p>His projects and experiences are separated into two pages which can be switched between using a button. Each project or experience is given a short description, but the format for the description is different from the projects page to the experiences page. In his projects, it is quite literally a short description, with a list of the technologies he used right after. In his experiences, it is much more like the format of a resume item, using bullet points and dating when the experience happened. I think it would have been nice to also include these bullet points for his projects, and also include the descriptions for his experiences. A combination of both is what I’m getting at here, because it is nice to have the resume item format so that the main target audience, recruiters, have a section to quickly skim through, but it is also nice to have a short description of what his experience was with that specific item to go beyond just a resume item. The website can and should be more than just a resume, and that comes from having the extra space to add more personal descriptions about how you enjoyed your time at a certain experience or working on a certain project.</p>
                <p>To continue on making the website more than just a resume, there can also be links included in each section to the specific place he had an experience in or the specific project that he has worked on to give more context.</p>
                <p>Overall, I do like how his site is simple and straightforward. It allows the main target audience, recruiters, to look through and quickly get a sense of who he is and his accomplishments. It might be the case that, with a multi page site like mine it is easy to get overwhelmed and not find the motivation to read through all the information.</p>
            </div>
        </div>
    )
}

export default Home;